

server :
 port : 8089
spring:

  datasource:

    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/mydbtest

    username: postgres

    password: 1234

  jpa:

    hibernate:

      ddl-auto: update

    show-sql: true

    database: postgresql

    database-platform: org.hibernate.dialect.PostgreSQLDialect

    open-in-view: false
  mvc:
   view:
     prefix: /WEB-INF/jsp/
     suffix: .jsp 
